# Permalinks
permalink:        pretty

# Setup
url: "http://unoebauer.github.io" # the base hostname & protocol for your site
title: Ulrich Noebauer

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl: "" # the subpath of your site, e.g. /blog

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  Astrophysicist, Post-doctoral Researcher and avid Amateur Photographer
#  A pretentious two-column [Jekyll](http://jekyllrb.com/) theme, stolen by [`@qwtel`](https://twitter.com/qwtel)
#  from [Hyde](http://hyde.getpoole.com).
#  You could say it was.. [hydejacked](http://media3.giphy.com/media/makedRIckZBW8/giphy.gif).

# The tags listed as entries in the sidebar
# sidebar_tags:     [jekyll, hyde]

# Fallback image and color if not overwritten for tag or post
image:            /public/img/SN1994D.jpg
color:            '#A85641'

author:
  name:           'Ulrich Noebauer'

  # Setting social media usernames will add icons at the bottom of the sidebar
  # twitter:        qwtel
  github:         unoebauer

  # Setting a disqus username will enable the comment section
  # disqus:         unoebauer

  # This photo will be used in the about section
  # photo:          http://qwtel.com/public/img/flo.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  # about:          |
  #   Astrophysicist, Post-doctoral Researcher and avid Amateur Photographer

kramdown:
  math_engine: mathjax
  math_engine_opts:
    preview: true
