# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ulrich Noebauer
email: unoebauer [at] mpa-garching.mpg.de
description: > # this means to ignore newlines until "baseurl:"
  Astrophysicist, Post-doctoral Researcher and avid Amateur Photographer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://unoebauer.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  unoebauer

# Build settings
markdown: kramdown
